-- MiMi Messenger database
-- Выполни весь этот SQL в Supabase SQL Editor.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  created_at timestamptz not null default now()
);

create table public.messages (
  id bigint generated by default as identity primary key,
  sender_id uuid not null references public.profiles(id) on delete cascade,
  receiver_id uuid not null references public.profiles(id) on delete cascade,
  body text not null check (char_length(body) > 0 and char_length(body) <= 5000),
  created_at timestamptz not null default now()
);

create index messages_sender_receiver_idx
on public.messages(sender_id, receiver_id, created_at);

create index messages_receiver_sender_idx
on public.messages(receiver_id, sender_id, created_at);

alter table public.profiles enable row level security;
alter table public.messages enable row level security;

create policy "profiles readable by authenticated users"
on public.profiles for select
to authenticated
using (true);

create policy "users can create own profile"
on public.profiles for insert
to authenticated
with check (id = auth.uid());

create policy "users can update own profile"
on public.profiles for update
to authenticated
using (id = auth.uid())
with check (id = auth.uid());

create policy "users can read their messages"
on public.messages for select
to authenticated
using (sender_id = auth.uid() or receiver_id = auth.uid());

create policy "users can send as themselves"
on public.messages for insert
to authenticated
with check (sender_id = auth.uid());

-- Realtime для новых сообщений
alter publication supabase_realtime add table public.messages;
